name: Send test email via AWS SES to developers on action update

on:
  push:
    paths:
      - '.github/workflows/on_action_update_send_test_email.yml'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-west-1'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email using AWS SES
        uses: CodeAtlas/action-aws-ses@v1.1.0
        with:
          to: ${{ vars.TEST_EMAIL_RECIPIENTS }}
          from: ${{ vars.NEW_ANDROID_RELEASE_EMAIL_TO }}
          reply_to: ${{ vars.NEW_ANDROID_RELEASE_EMAIL_REPLY_TO }}
          subject: ${{ vars.NEW_ANDROID_RELEASE_EMAIL_SUBJECT }}
          body_html: ${{ vars.NEW_ANDROID_RELEASE_EMAIL_BODY }}